apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ecs0n1z60-python 
  janus-idp.io/tekton: ecs0n1z60-python
  backstage.io/kubernetes-id: ecs0n1z60-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ecs0n1z60-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml